return {
    -- "neovim/nvim-lspconfig",
    -- enabled = true,
    -- -- opts = {
    -- --     servers = {
    -- --         ["*"] = {
    -- --             keys = {
    -- --                 -- { "gd", false },
    -- --             },
    -- --         },
    -- --         ts_ls = {
    -- --             keys = {
    -- --                 -- { "gr", false },
    -- --             },
    -- --         },
    -- --         vtsls = {
    -- --             keys = {
    -- --                 -- { "gr", false },
    -- --             },
    -- --         },
    -- --         angularls = {
    -- --             keys = {
    -- --                 -- { "gd", false },
    -- --             },
    -- --         },
    -- --     },
    -- -- },
    -- -- opts = function()
    -- -- local keys = require("lazyvim.plugins.lsp.keymaps").get()
    -- -- keys[#keys + 1] = { "<leader>gr", false }
    -- --
    -- -- end,
    -- opts = {
    --     servers = {
    --         angularls = {},
    --     },
    --     setup = {
    --         -- angularls = function()
    --         --   Snacks.util.lsp.on({ name = "angularls" }, function(_, client)
    --         --     --HACK: disable angular renaming capability due to duplicate rename popping up
    --         --     client.server_capabilities.renameProvider = true
    --         --   end)
    --         -- end,
    --     },
    -- },
    -- -- config = function()
    -- -- local lspconfig = require("lspconfig")
    -- -- lspconfig.vtsls.setup({})
    -- -- lspconfig.angularls.setup({})
    -- -- end,
}
